# File: app/kb.py
# -*- coding: utf-8 -*-
from typing import Dict, List, Any

KB: List[Dict[str, Any]] = [
    {"name":"운영체제 발달 과정","mnemonic":"일시다범분","items":["일괄 처리 시스템","시분할 시스템","다중 처리 시스템","범용 시스템","분산 처리 시스템"]},
    {"name":"메모리 관리 기법","mnemonic":"반배할교","items":["반입기법","배치기법","할당기법","교체 기법"]},
    {"name":"배치 기법의 유형","mnemonic":"초적악","items":["최초 적합","최적 적합","최악 적합"]},
    {"name":"지역성의 유형","mnemonic":"시공순","items":["시간 지역성","공간 지역성","순차 지역성"]},
    {"name":"프로세스 상태","mnemonic":"생준 실대완","items":["생성","준비","실행","대기","완료"]},
    {"name":"선점 스케줄링 알고리즘","mnemonic":"SMMR","items":["SRT","MLQ","MLFQ","Round Robin"]},
    {"name":"비선점 스케줄링 알고리즘","mnemonic":"우기 HFS","items":["우선순위","기한부","HRN","FCFS","SJF"]},
    {"name":"HRN의 우선순위","mnemonic":"대서서","items":["(대기시간 + 서비스시간) / 서비스시간"]},
    {"name":"반환/대기시간 계산","mnemonic":"반종도 대반서","items":["반환시간 = 종료시간 - 도착시간","대기시간 = 반환시간 - 서비스시간"]},
    {"name":"교착상태 발생 조건","mnemonic":"상점비환","items":["상호배제","점유와 대기","비선점","환형대기"]},
    {"name":"교착상태 해결 방법","mnemonic":"예회발복","items":["예방","회피","발견","복구"]},
    {"name":"OSI 7계층","mnemonic":"아파서 티내다, 피나다","items":["Application(7)","Presentation(6)","Session(5)","Transport(4)","Network(3)","Data Link(2)","Physical(1)"]},
    {"name":"WAN 연결기술","mnemonic":"전회패","items":["전용 회선 방식","회선 교환 방식","패킷 교환 방식"]},
    {"name":"프로토콜 기본 3요소","mnemonic":"구의타","items":["구문","의미","타이밍"]},
    {"name":"ARQ 종류","mnemonic":"스고셀","items":["Stop-and-Wait ARQ","Goback-N ARQ","Selective Repeat ARQ"]},
    {"name":"IPv4 전송방식","mnemonic":"유멀브","items":["유니캐스트","멀티캐스트","브로드캐스트"]},
    {"name":"IPv6 전송방식","mnemonic":"유멀애","items":["유니캐스트","멀티캐스트","애니캐스트"]},
    {"name":"TCP 특징","mnemonic":"신연흐혼","items":["신뢰성 보장","연결 지향적","흐름제어","혼잡제어"]},
    {"name":"RAID 0과 1","mnemonic":"0스 1미","items":["RAID 0 - 스트라이핑","RAID 1 - 미러링"]},
    {"name":"클라우드 컴퓨팅 분류","mnemonic":"사공하","items":["사설 클라우드","공용 클라우드","하이브리드 클라우드"]},
    {"name":"클라우드 서비스 유형","mnemonic":"인플소","items":["IaaS","PaaS","SaaS"]},
    {"name":"UI 유형","mnemonic":"CG NO","items":["CLI","GUI","NUI","OUI"]},
    {"name":"UI 설계 원칙","mnemonic":"직유 학유","items":["직관성","유효성","학습성","유연성"]},
    {"name":"UI 화면 설계 구분","mnemonic":"와스프","items":["와이어 프레임","스토리보드","프로토타입"]},
    {"name":"연산자 우선 순위","mnemonic":"증산시 관비 논삼대","items":["증감 연산자","산술 연산자","시프트 연산자","관계 연산자","비트 연산자","논리 연산자","삼항 연산자","대입 연산자"]},
    {"name":"데이터 모델링 절차","mnemonic":"요개논물","items":["요구사항 분석","개념적 설계","논리적 설계","물리적 설계"]},
    {"name":"관계 대수와 해석","mnemonic":"대절해비","items":["관계 대수는 절차적 언어","관계 해석은 비절차적 언어"]},
    {"name":"일반 집합 연산","mnemonic":"합교차카","items":["합집합","교집합","차집합","카디션 프로덕트"]},
    {"name":"순수 관계 연산자","mnemonic":"셀프조디","items":["셀렉트","프로젝트","조인","디비전"]},
    {"name":"논리 데이터 모델링 속성","mnemonic":"개속관","items":["개체","속성","관계"]},
    {"name":"이상 현상","mnemonic":"삽삭갱","items":["삽입이상","삭제이상","갱신이상"]},
    {"name":"무결성 종류","mnemonic":"개참속사키","items":["개체 무결성","참조 무결성","속성 무결성","사용자 무결성","키 무결"]},
    {"name":"데이터 마이닝 기법","mnemonic":"분연 연데","items":["분류 규칙","연관 규칙","연속 규칙","데이터 군집화"]},
    {"name":"트랜잭션 특성","mnemonic":"ACID","items":["Atomicity","Consistency","Isolation","Durability"]},
    {"name":"트랜잭션 상태","mnemonic":"활부완실철","items":["활동","부분완료","완료","실패","철회"]},
    {"name":"TCL 명령어","mnemonic":"커롤체","items":["COMMIT","ROLLBACK","CHECKPOINT"]},
    {"name":"DDL 명령어","mnemonic":"크알드트","items":["CREATE","ALTER","DROP","TRUNCATE"]},
    {"name":"DML 명령어","mnemonic":"세인업데","items":["SELECT","INSERT","UPDATE","DELETE"]},
    {"name":"SELECT 명령문 순서","mnemonic":"셀프 웨 구해오","items":["SELECT","FROM","WHERE","GROUP BY","HAVING","ORDER BY"]},
    {"name":"INSERT 명령문","mnemonic":"인인벨","items":["INSERT INTO","VALUES"]},
    {"name":"UPDATE 명령문","mnemonic":"업셋웨","items":["UPDATE","SET","WHERE"]},
    {"name":"DELETE 명령문","mnemonic":"딜프웨","items":["DELETE FROM","WHERE"]},
    {"name":"GRANT 명령어","mnemonic":"그온투","items":["GRANT 권한","ON 테이블","TO 사용자"]},
    {"name":"REVOKE 명령어","mnemonic":"리온프","items":["REVOKE 권한","ON 테이블","FROM 사용자"]},
    {"name":"화이트박스 테스트","mnemonic":"구결조 조변다 기제데루","items":["구문 커버리지","결정 커버리지","조건 커버리지","조건-결정 커버리지","변경 커버리지","다중 조건 커버리지","기본 경로 커버리지","제어 흐름 테스트","데이터 흐름 테스트","루프 테스트"]},
    {"name":"블랙박스 테스트","mnemonic":"동경결상 유분페윈비오","items":["동등분할 테스트","경곗값 분석 테스트","결정 테이블 테스트","상태 전이 테스트","유스케이스 테스트","분류트리 테스트","페어와이즈 테스트","원인-결과 그래프 테스트","비교 테스트","오류추정 테스트"]},
    {"name":"테스트 커버리지","mnemonic":"기라코","items":["기능 기반 커버리지","라인 커버리지","코드 커버리지"]},
    {"name":"테스트 레벨","mnemonic":"단통시인","items":["단위 테스트","통합 테스트","시스템 테스트","인수 테스트"]},
    {"name":"통합수행 방식","mnemonic":"하스 상드","items":["하향식 - 스텁","상향식 - 드라이버"]},
    {"name":"클린 코드 원칙","mnemonic":"가단의 증추","items":["가독성","단순성","의존성 최소","중복성 제거","추상화"]},
    {"name":"패키징 도구 구성요소","mnemonic":"(암/키/식/저/암/정/크/인)","items":["암호화","키 관리","식별 기술","저작권 표현","암호화 파일 생성","정책 관리","크랙방지","인증"]},
]

GLOSSARY: Dict[str, Dict[str, str]] = {
    it: {"category": cat["name"], "mnemonic": cat["mnemonic"]}
    for cat in KB for it in cat["items"]
}
